name: Lets run the script every hour, to make sure we get notification when the stock comes.

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:     # Allow manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        TWILIO_PHONE: ${{ secrets.TWILIO_PHONE }}
        MY_PHONE: ${{ secrets.MY_PHONE }}
      run: python main.py